// Generated by Apple Swift version 4.1 (swiftlang-902.0.48 clang-902.0.37.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR __attribute__((enum_extensibility(open)))
# else
#  define SWIFT_ENUM_ATTR
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CVCalendar",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIColor;
@class CVCalendarDayView;
@class NSCoder;

SWIFT_CLASS("_TtC10CVCalendar15CVAuxiliaryView")
@interface CVAuxiliaryView : UIView
@property (nonatomic, strong) UIColor * _Null_unspecified strokeColor SWIFT_DEPRECATED_OBJC("Swift property 'CVAuxiliaryView.strokeColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Null_unspecified fillColor SWIFT_DEPRECATED_OBJC("Swift property 'CVAuxiliaryView.fillColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, strong) UIColor * _Nonnull defaultFillColor SWIFT_DEPRECATED_OBJC("Swift property 'CVAuxiliaryView.defaultFillColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, assign) CVCalendarDayView * _Nonnull dayView SWIFT_DEPRECATED_OBJC("Swift property 'CVAuxiliaryView.dayView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didMoveToSuperview;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface CVAuxiliaryView (SWIFT_EXTENSION(CVCalendar))
- (void)updateFrame:(CGRect)frame SWIFT_DEPRECATED_OBJC("Swift method 'CVAuxiliaryView.updateFrame(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



@class CVCalendarView;
@class UIScrollView;
@class CVCalendarMonthView;
@class NSBundle;

SWIFT_CLASS("_TtC10CVCalendar31CVCalendarContentViewController")
@interface CVCalendarContentViewController : UIViewController
@property (nonatomic, readonly, copy) NSString * _Nonnull previous SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.previous' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSString * _Nonnull presented SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.presented' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSString * _Nonnull following SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.following' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, assign) CVCalendarView * _Nonnull calendarView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.calendarView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, strong) UIScrollView * _Nonnull scrollView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.scrollView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CVCalendarMonthView * _Nonnull presentedMonthView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.presentedMonthView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) CGRect bounds SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.bounds' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) NSInteger currentPage SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.currentPage' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL pageChanged SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.pageChanged' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL pageLoadingEnabled SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.pageLoadingEnabled' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL presentationEnabled SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.presentationEnabled' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) CGFloat lastContentOffset SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.lastContentOffset' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) double toggleDateAnimationDuration SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarContentViewController.toggleDateAnimationDuration' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView frame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarContentViewController.init(calendarView:frame:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil SWIFT_UNAVAILABLE;
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar)) <UIScrollViewDelegate>
@end






@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)refreshPresentedMonth SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.refreshPresentedMonth()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)updateFrames:(CGRect)frame;
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (NSInteger)indexOfIdentifier:(NSString * _Nonnull)identifier SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.indexOfIdentifier(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)updateHeight:(CGFloat)height animated:(BOOL)animated SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.updateHeight(_:animated:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateLayoutIfNeeded SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.updateLayoutIfNeeded()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class CVDate;

@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (NSDate * _Nonnull)dateBeforeDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.dateBeforeDate(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (NSDate * _Nonnull)dateAfterDate:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.dateAfterDate(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (BOOL)matchedMonths:(CVDate * _Nonnull)lhs :(CVDate * _Nonnull)rhs SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.matchedMonths(_:_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (BOOL)matchedWeeks:(CVDate * _Nonnull)lhs :(CVDate * _Nonnull)rhs SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.matchedWeeks(_:_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (BOOL)matchedDays:(CVDate * _Nonnull)lhs :(CVDate * _Nonnull)rhs SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarContentViewController.matchedDays(_:_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
@end

@class CVCalendarWeekView;
@class UILabel;
@class CALayer;

SWIFT_CLASS("_TtC10CVCalendar17CVCalendarDayView")
@interface CVCalendarDayView : UIView
@property (nonatomic, weak) CVCalendarWeekView * _Null_unspecified weekView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.weekView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CVDate * _Null_unspecified date SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.date' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UILabel * _Null_unspecified dayLabel SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.dayLabel' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CVAuxiliaryView * _Nullable selectionView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.selectionView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CALayer * _Nullable topMarker SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.topMarker' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL isHighlighted SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.isHighlighted' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL isOut SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.isOut' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL isCurrentDay SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.isCurrentDay' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL isDisabled SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.isDisabled' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, weak) CVCalendarMonthView * _Null_unspecified monthView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.monthView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, weak) CVCalendarView * _Null_unspecified calendarView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarDayView.calendarView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) CGRect frame;
- (nonnull instancetype)initWithWeekView:(CVCalendarWeekView * _Nonnull)weekView weekdayIndex:(NSInteger)weekdayIndex OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarDayView.init(weekView:weekdayIndex:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CVDate * _Nonnull)dateWithWeekView:(CVCalendarWeekView * _Nonnull)weekView andWeekIndex:(NSInteger)index SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.dateWithWeekView(_:andWeekIndex:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end




@interface CVCalendarDayView (SWIFT_EXTENSION(CVCalendar))
- (void)reloadContent SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.reloadContent()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarDayView (SWIFT_EXTENSION(CVCalendar))
- (void)moveDotMarkerBack:(BOOL)unwinded coloring:(BOOL)coloring SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.moveDotMarkerBack(_:coloring:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarDayView (SWIFT_EXTENSION(CVCalendar))
- (CGPoint)pointAtAngle:(CGFloat)angle withinCircleView:(UIView * _Nonnull)circleView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.pointAtAngle(_:withinCircleView:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)moveView:(UIView * _Nonnull)view onCircleView:(UIView * _Nonnull)circleView fromAngle:(CGFloat)angle toAngle:(CGFloat)endAngle straight:(BOOL)straight SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.moveView(_:onCircleView:fromAngle:toAngle:straight:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarDayView (SWIFT_EXTENSION(CVCalendar))
- (void)setDeselectedWithClearing:(BOOL)clearing SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.setDeselectedWithClearing(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarDayView (SWIFT_EXTENSION(CVCalendar))
- (void)labelSetup SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.labelSetup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)interactionSetup SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.interactionSetup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)preliminarySetup SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.preliminarySetup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)supplementarySetup SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.supplementarySetup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)topMarkerSetup SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.topMarkerSetup()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupDotMarker SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarDayView.setupDotMarker()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UIFont;
@protocol CVCalendarMenuViewDelegate;

SWIFT_CLASS("_TtC10CVCalendar18CVCalendarMenuView")
@interface CVCalendarMenuView : UIView
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull symbols SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.symbols' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<UILabel *> * _Nullable symbolViews SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.symbolViews' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayOfWeekTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.dayOfWeekTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayofWeekBackgroundColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.dayofWeekBackgroundColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayOfWeekFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.dayOfWeekFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSCalendar * _Nullable calendar SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.calendar' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, weak) IBOutlet id _Nullable menuViewDelegate;
@property (nonatomic, weak) id <CVCalendarMenuViewDelegate> _Nullable delegate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMenuView.delegate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)setupAppearance SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMenuView.setupAppearance()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupWeekdaySymbols SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMenuView.setupWeekdaySymbols()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)createDaySymbols SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMenuView.createDaySymbols()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)commitMenuViewUpdate SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMenuView.commitMenuViewUpdate()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

enum CVCalendarWeekday : NSInteger;
enum CVWeekdaySymbolType : NSInteger;

SWIFT_PROTOCOL("_TtP10CVCalendar26CVCalendarMenuViewDelegate_")
@protocol CVCalendarMenuViewDelegate
@optional
- (enum CVCalendarWeekday)firstWeekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekTextColorBy:(enum CVCalendarWeekday)weekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekBackGroundColorBy:(enum CVCalendarWeekday)weekday SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayOfWeekBackGroundColor SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dayOfWeekTextUppercase SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayOfWeekFont SWIFT_WARN_UNUSED_RESULT;
- (enum CVWeekdaySymbolType)weekdaySymbolType SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC10CVCalendar36CVCalendarMonthContentViewController")
@interface CVCalendarMonthContentViewController : CVCalendarContentViewController
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView frame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView frame:(CGRect)frame presentedDate:(NSDate * _Nonnull)presentedDate OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarMonthContentViewController.init(calendarView:frame:presentedDate:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)initialLoad:(NSDate * _Nonnull)date SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.initialLoad(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)reloadMonthViews SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.reloadMonthViews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)insertMonthView:(CVCalendarMonthView * _Nonnull)monthView withIdentifier:(NSString * _Nonnull)identifier SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.insertMonthView(_:withIdentifier:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)replaceMonthView:(CVCalendarMonthView * _Nonnull)monthView withIdentifier:(NSString * _Nonnull)identifier animatable:(BOOL)animatable SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.replaceMonthView(_:withIdentifier:animatable:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)scrolledLeft SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.scrolledLeft()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)scrolledRight SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.scrolledRight()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateFrames:(CGRect)rect;
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
@end


@interface CVCalendarMonthContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)prepareTopMarkersOnMonthView:(CVCalendarMonthView * _Nonnull)monthView hidden:(BOOL)hidden SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.prepareTopMarkersOnMonthView(_:hidden:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateSelection SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.updateSelection()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)selectDayViewWithDay:(NSInteger)day inMonthView:(CVCalendarMonthView * _Nonnull)monthView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.selectDayViewWithDay(_:inMonthView:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarMonthContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
@end


@interface CVCalendarMonthContentViewController (SWIFT_EXTENSION(CVCalendar))
- (CVCalendarMonthView * _Nonnull)getFollowingMonth:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.getFollowingMonth(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CVCalendarMonthView * _Nonnull)getPreviousMonth:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthContentViewController.getPreviousMonth(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_CLASS("_TtC10CVCalendar19CVCalendarMonthView")
@interface CVCalendarMonthView : UIView
@property (nonatomic) CGRect frame;
@property (nonatomic, weak) CVCalendarView * _Null_unspecified calendarView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.calendarView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSDate * _Null_unspecified date SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.date' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<CVCalendarWeekView *> * _Null_unspecified weekViews SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.weekViews' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSDictionary<NSNumber *, NSArray<NSNumber *> *> *> * _Nullable weeksIn SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.weeksIn' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<NSDictionary<NSNumber *, NSArray<NSNumber *> *> *> * _Nullable weeksOut SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.weeksOut' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) CGSize potentialSize SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarMonthView.potentialSize' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView date:(NSDate * _Nonnull)date OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarMonthView.init(calendarView:date:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)mapDayViews:(SWIFT_NOESCAPE void (^ _Nonnull)(CVCalendarDayView * _Nonnull))body SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.mapDayViews(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end




@interface CVCalendarMonthView (SWIFT_EXTENSION(CVCalendar))
- (void)commonInit SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.commonInit()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarMonthView (SWIFT_EXTENSION(CVCalendar))
- (void)reloadViewsWithRect:(CGRect)frame SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.reloadViewsWithRect(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarMonthView (SWIFT_EXTENSION(CVCalendar))
- (void)updateAppearance:(CGRect)frame SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.updateAppearance(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)createWeekViews SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.createWeekViews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

@class UILongPressGestureRecognizer;
@class UITapGestureRecognizer;

@interface CVCalendarMonthView (SWIFT_EXTENSION(CVCalendar))
- (void)updateInteractiveView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarMonthView.updateInteractiveView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didPressInteractiveView:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (void)didTouchInteractiveView:(UITapGestureRecognizer * _Nonnull)recognizer;
@end

@class CVCalendarViewAppearance;
@protocol CVCalendarViewDelegate;

SWIFT_CLASS("_TtC10CVCalendar14CVCalendarView")
@interface CVCalendarView : UIView
@property (nonatomic, strong) CVCalendarViewAppearance * _Null_unspecified appearance SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.appearance' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CVCalendarContentViewController * _Null_unspecified contentController SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.contentController' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) enum CVCalendarWeekday firstWeekday SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.firstWeekday' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) CVDate * _Null_unspecified presentedDate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.presentedDate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL shouldAnimateResizing SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.shouldAnimateResizing' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL shouldAutoSelectDayOnMonthChange SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.shouldAutoSelectDayOnMonthChange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL shouldAutoSelectDayOnWeekChange SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.shouldAutoSelectDayOnWeekChange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL shouldScrollOnOutDayViewSelection SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.shouldScrollOnOutDayViewSelection' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) BOOL shouldSelectRange SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.shouldSelectRange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDate * _Nullable disableScrollingBeforeDate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.disableScrollingBeforeDate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDate * _Nullable disableScrollingBeyondDate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.disableScrollingBeyondDate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) NSInteger maxSelectableRange SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.maxSelectableRange' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDate * _Nullable earliestSelectableDate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.earliestSelectableDate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSDate * _Nullable latestSelectableDate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.latestSelectableDate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, weak) IBOutlet id _Nullable calendarDelegate;
@property (nonatomic, weak) id <CVCalendarViewDelegate> _Nullable delegate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarView.delegate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, weak) IBOutlet id _Nullable calendarAppearanceDelegate;
@property (nonatomic, weak) IBOutlet id _Nullable animatorDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface CVCalendarView (SWIFT_EXTENSION(CVCalendar))
- (void)commitCalendarViewUpdate SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.commitCalendarViewUpdate()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarView (SWIFT_EXTENSION(CVCalendar))
- (void)didSelectDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.didSelectDayView(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end



enum CVCalendarViewPresentationMode : NSInteger;

@interface CVCalendarView (SWIFT_EXTENSION(CVCalendar))
- (void)changeDaysOutShowingStateWithShouldShow:(BOOL)shouldShow SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.changeDaysOutShowingState(shouldShow:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)toggleViewWithDate:(NSDate * _Nonnull)date SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.toggleViewWithDate(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)toggleCurrentDayView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.toggleCurrentDayView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)loadNextView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.loadNextView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)loadPreviousView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.loadPreviousView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)changeMode:(enum CVCalendarViewPresentationMode)mode completion:(void (^ _Nonnull)(void))completion SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarView.changeMode(_:completion:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


SWIFT_PROTOCOL("_TtP10CVCalendar30CVCalendarViewAnimatorDelegate_")
@protocol CVCalendarViewAnimatorDelegate
- (void (^ _Nonnull)(CVCalendarDayView * _Nonnull, void (^ _Nonnull)(BOOL)))selectionAnimation SWIFT_WARN_UNUSED_RESULT;
- (void (^ _Nonnull)(CVCalendarDayView * _Nonnull, void (^ _Nonnull)(BOOL)))deselectionAnimation SWIFT_WARN_UNUSED_RESULT;
@end

@protocol CVCalendarViewAppearanceDelegate;

SWIFT_CLASS("_TtC10CVCalendar24CVCalendarViewAppearance")
@interface CVCalendarViewAppearance : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, strong) UIFont * _Nullable dayLabelWeekdayFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelPresentWeekdayFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelPresentWeekdayBoldFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayBoldFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelPresentWeekdayHighlightedFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayHighlightedFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelPresentWeekdaySelectedFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdaySelectedFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelWeekdayHighlightedFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayHighlightedFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIFont * _Nullable dayLabelWeekdaySelectedFont SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdaySelectedFont' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Default text color.
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdayDisabledColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayDisabledColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdayInTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayInTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdayOutTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayOutTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdayHighlightedTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayHighlightedTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdaySelectedTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdaySelectedTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelPresentWeekdayTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelPresentWeekdayHighlightedTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayHighlightedTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelPresentWeekdaySelectedTextColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdaySelectedTextColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Default highlighted state background & alpha.
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdayHighlightedBackgroundColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdayHighlightedBackgroundColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelPresentWeekdayHighlightedBackgroundColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdayHighlightedBackgroundColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Default selected state background & alpha.
@property (nonatomic, strong) UIColor * _Nullable dayLabelWeekdaySelectedBackgroundColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelWeekdaySelectedBackgroundColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dayLabelPresentWeekdaySelectedBackgroundColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dayLabelPresentWeekdaySelectedBackgroundColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, strong) UIColor * _Nullable dotMarkerColor SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.dotMarkerColor' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, weak) id <CVCalendarViewAppearanceDelegate> _Nullable delegate SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarViewAppearance.delegate' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)setupAppearance SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarViewAppearance.setupAppearance()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

enum CVStatus : NSInteger;
enum CVPresent : NSInteger;

SWIFT_PROTOCOL("_TtP10CVCalendar32CVCalendarViewAppearanceDelegate_")
@protocol CVCalendarViewAppearanceDelegate
@optional
- (CGFloat)spaceBetweenWeekViews SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)spaceBetweenDayViews SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelFontBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dayLabelPresentWeekdayInitallyBold SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdayFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayBoldFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdayHighlightedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelPresentWeekdaySelectedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdayHighlightedFont SWIFT_WARN_UNUSED_RESULT;
- (UIFont * _Nonnull)dayLabelWeekdaySelectedFont SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)dayLabelColorBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayDisabledColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayInTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayOutTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayHighlightedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdaySelectedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayHighlightedTextColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdaySelectedTextColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelSizeBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayHighlightedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdaySelectedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayHighlightedTextSize SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdaySelectedTextSize SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nullable)dayLabelBackgroundColorBy:(enum CVCalendarWeekday)weekDay status:(enum CVStatus)status present:(enum CVPresent)present SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdayHighlightedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdayHighlightedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdayHighlightedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdayHighlightedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelWeekdaySelectedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelWeekdaySelectedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dayLabelPresentWeekdaySelectedBackgroundColor SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dayLabelPresentWeekdaySelectedBackgroundAlpha SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)dotMarkerColor SWIFT_WARN_UNUSED_RESULT;
- (UIColor * _Nonnull)topMarkerColor SWIFT_WARN_UNUSED_RESULT;
@end

@class UIBezierPath;

SWIFT_PROTOCOL("_TtP10CVCalendar22CVCalendarViewDelegate_")
@protocol CVCalendarViewDelegate
- (enum CVCalendarViewPresentationMode)presentationMode SWIFT_WARN_UNUSED_RESULT;
- (enum CVCalendarWeekday)firstWeekday SWIFT_WARN_UNUSED_RESULT;
@optional
- (BOOL)shouldAnimateResizing SWIFT_WARN_UNUSED_RESULT;
- (double)toggleDateAnimationDuration SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldScrollOnOutDayViewSelection SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAutoSelectDayOnWeekChange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldAutoSelectDayOnMonthChange SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowWeekdaysOut SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldSelectDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectDayView:(CVCalendarDayView * _Nonnull)dayView animationDidFinish:(BOOL)animationDidFinish;
- (void)presentedDateUpdated:(CVDate * _Nonnull)date;
- (BOOL)topMarkerWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dotMarkerWithShouldMoveOnHighlightingOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)dotMarkerWithShouldShowOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (NSArray<UIColor *> * _Nonnull)dotMarkerWithColorOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dotMarkerWithMoveOffsetOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)dotMarkerWithSizeOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (UIBezierPath * _Nonnull (^ _Nonnull)(CGRect))selectionViewPath SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldShowCustomSingleSelection SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)preliminaryViewWithViewOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)preliminaryViewWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nonnull)supplementaryViewWithViewOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (BOOL)supplementaryViewWithShouldDisplayOnDayView:(CVCalendarDayView * _Nonnull)dayView SWIFT_WARN_UNUSED_RESULT;
- (void)didShowNextMonthView:(NSDate * _Nonnull)date;
- (void)didShowPreviousMonthView:(NSDate * _Nonnull)date;
- (NSCalendar * _Nullable)calendar SWIFT_WARN_UNUSED_RESULT;
- (BOOL)shouldSelectRange SWIFT_WARN_UNUSED_RESULT;
- (void)didSelectRangeFrom:(CVCalendarDayView * _Nonnull)startDayView to:(CVCalendarDayView * _Nonnull)endDayView;
- (NSDate * _Nonnull)disableScrollingBeforeDate SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)disableScrollingBeyondDate SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)maxSelectableRange SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)earliestSelectableDate SWIFT_WARN_UNUSED_RESULT;
- (NSDate * _Nonnull)latestSelectableDate SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, CVCalendarViewPresentationMode) {
  CVCalendarViewPresentationModeMonthView = 0,
  CVCalendarViewPresentationModeWeekView = 1,
};


SWIFT_CLASS("_TtC10CVCalendar35CVCalendarWeekContentViewController")
@interface CVCalendarWeekContentViewController : CVCalendarContentViewController
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView frame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCalendarView:(CVCalendarView * _Nonnull)calendarView frame:(CGRect)frame presentedDate:(NSDate * _Nonnull)presentedDate OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarWeekContentViewController.init(calendarView:frame:presentedDate:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)initialLoad:(NSDate * _Nonnull)date SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.initialLoad(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)reloadWeekViews SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.reloadWeekViews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)insertWeekView:(CVCalendarWeekView * _Nonnull)weekView withIdentifier:(NSString * _Nonnull)identifier SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.insertWeekView(_:withIdentifier:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)replaceWeekView:(CVCalendarWeekView * _Nonnull)weekView withIdentifier:(NSString * _Nonnull)identifier animatable:(BOOL)animatable SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.replaceWeekView(_:withIdentifier:animatable:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)scrolledLeft SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.scrolledLeft()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)scrolledRight SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.scrolledRight()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateFrames:(CGRect)rect;
- (void)performedDayViewSelection:(CVCalendarDayView * _Nonnull)dayView;
- (void)presentPreviousView:(UIView * _Nullable)view;
- (void)presentNextView:(UIView * _Nullable)view;
- (void)updateDayViewsWithShouldShow:(BOOL)shouldShow;
- (void)togglePresentedDate:(NSDate * _Nonnull)date;
@end


@interface CVCalendarWeekContentViewController (SWIFT_EXTENSION(CVCalendar))
- (CVCalendarMonthView * _Nonnull)getFollowingMonth:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.getFollowingMonth(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CVCalendarMonthView * _Nonnull)getPreviousMonth:(NSDate * _Nonnull)date SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.getPreviousMonth(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarWeekContentViewController (SWIFT_EXTENSION(CVCalendar))
- (CVCalendarWeekView * _Nullable)getPresentedWeek SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.getPresentedWeek()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CVCalendarWeekView * _Nonnull)getPreviousWeek:(CVCalendarWeekView * _Nonnull)presentedWeekView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.getPreviousWeek(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (CVCalendarWeekView * _Nonnull)getFollowingWeek:(CVCalendarWeekView * _Nonnull)presentedWeekView SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.getFollowingWeek(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarWeekContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)prepareTopMarkersOnWeekView:(CVCalendarWeekView * _Nonnull)weekView hidden:(BOOL)hidden SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.prepareTopMarkersOnWeekView(_:hidden:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)updateSelection SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.updateSelection()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)selectDayViewWithDay:(NSInteger)day inWeekView:(CVCalendarWeekView * _Nonnull)weekView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekContentViewController.selectDayViewWithDay(_:inWeekView:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarWeekContentViewController (SWIFT_EXTENSION(CVCalendar))
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewWillBeginDragging:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDecelerating:(UIScrollView * _Nonnull)scrollView;
- (void)scrollViewDidEndDragging:(UIScrollView * _Nonnull)scrollView willDecelerate:(BOOL)decelerate;
@end


SWIFT_CLASS("_TtC10CVCalendar18CVCalendarWeekView")
@interface CVCalendarWeekView : UIView
@property (nonatomic) CGRect frame;
@property (nonatomic, weak) CVCalendarMonthView * _Null_unspecified monthView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.monthView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSArray<CVCalendarDayView *> * _Null_unspecified dayViews SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.dayViews' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSDictionary<NSNumber *, NSArray<NSNumber *> *> * _Nullable weekdaysIn SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.weekdaysIn' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, copy) NSDictionary<NSNumber *, NSArray<NSNumber *> *> * _Nullable weekdaysOut SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.weekdaysOut' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic) BOOL utilizable SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.utilizable' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
/// Recovery service.
@property (nonatomic, readonly, weak) CVCalendarView * _Null_unspecified calendarView SWIFT_DEPRECATED_OBJC("Swift property 'CVCalendarWeekView.calendarView' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithMonthView:(CVCalendarMonthView * _Nonnull)monthView index:(NSInteger)index OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVCalendarWeekView.init(monthView:index:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)mapDayViews:(SWIFT_NOESCAPE void (^ _Nonnull)(CVCalendarDayView * _Nonnull))body SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekView.mapDayViews(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end




@interface CVCalendarWeekView (SWIFT_EXTENSION(CVCalendar))
- (void)createDayViews SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekView.createDayViews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)reloadDayViews SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekView.reloadDayViews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVCalendarWeekView (SWIFT_EXTENSION(CVCalendar))
- (void)updateInteractiveView SWIFT_DEPRECATED_OBJC("Swift method 'CVCalendarWeekView.updateInteractiveView()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (void)didPressInteractiveView:(UILongPressGestureRecognizer * _Nonnull)recognizer;
- (void)didTouchInteractiveView:(UITapGestureRecognizer * _Nonnull)recognizer;
@end

typedef SWIFT_ENUM(NSInteger, CVCalendarWeekday) {
  CVCalendarWeekdaySunday = 1,
  CVCalendarWeekdayMonday = 2,
  CVCalendarWeekdayTuesday = 3,
  CVCalendarWeekdayWednesday = 4,
  CVCalendarWeekdayThursday = 5,
  CVCalendarWeekdayFriday = 6,
  CVCalendarWeekdaySaturday = 7,
};


SWIFT_CLASS("_TtC10CVCalendar6CVDate")
@interface CVDate : NSObject
@property (nonatomic, readonly) NSInteger year SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.year' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) NSInteger month SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.month' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) NSInteger week SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.week' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly) NSInteger day SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.day' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithDate:(NSDate * _Nonnull)date calendar:(NSCalendar * _Nonnull)calendar OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVDate.init(date:calendar:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)initWithDay:(NSInteger)day month:(NSInteger)month week:(NSInteger)week year:(NSInteger)year calendar:(NSCalendar * _Nonnull)calendar OBJC_DESIGNATED_INITIALIZER SWIFT_DEPRECATED_OBJC("Swift initializer 'CVDate.init(day:month:week:year:calendar:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end




@interface CVDate (SWIFT_EXTENSION(CVCalendar))
- (NSDate * _Nullable)convertedDateWithCalendar:(NSCalendar * _Nonnull)calendar SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'CVDate.convertedDate(calendar:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface CVDate (SWIFT_EXTENSION(CVCalendar))
@property (nonatomic, readonly, copy) NSString * _Nonnull globalDescription SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.globalDescription' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@property (nonatomic, readonly, copy) NSString * _Nonnull commonDescription SWIFT_DEPRECATED_OBJC("Swift property 'CVDate.commonDescription' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

typedef SWIFT_ENUM(NSInteger, CVPresent) {
  CVPresentPresent = 0,
  CVPresentNot = 1,
};

typedef SWIFT_ENUM(NSInteger, CVStatus) {
  CVStatusIn = 0,
  CVStatusOut = 1,
  CVStatusDisabled = 2,
  CVStatusSelected = 3,
  CVStatusHighlighted = 4,
};

typedef SWIFT_ENUM(NSInteger, CVWeekdaySymbolType) {
  CVWeekdaySymbolTypeNormal = 0,
  CVWeekdaySymbolTypeShort = 1,
  CVWeekdaySymbolTypeVeryShort = 2,
};


@interface UIColor (SWIFT_EXTENSION(CVCalendar))
+ (UIColor * _Nonnull)colorFromCode:(NSInteger)code SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_OBJC("Swift method 'UIColor.colorFromCode(_:)' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end


@interface UIView (SWIFT_EXTENSION(CVCalendar))
- (void)removeAllSubviews SWIFT_DEPRECATED_OBJC("Swift method 'UIView.removeAllSubviews()' uses '@objc' inference deprecated in Swift 4; add '@objc' to provide an Objective-C entrypoint");
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
